branches: main

variables:
  - &file Containerfile
  - &repo github.com/${CI_REPO_OWNER}/telegram-video-bot

pipeline:

  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: linux/amd64
      repo: *repo
      registry:
        from_secret: registry-host
      tags: latest
      username: 
        from_secret: registry-user
      password:
        from_secret: registry-password
    when:
      event: push
      path: *file
