branches: main

pipeline:
  publish:
    image: plugins/docker
    settings:
      dockerfile: Containerfile
      repo: registry-internal.default.svc.cluster.local/testings3
      tags: latest
      username: 
        from_secret: registry-user
      password:
        from_secret: registry-password
    when:
      event: push
