pipeline:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Containerfile
      platforms: linux/amd64
      repo:
        from_secret: TARGET_REPOSITORY
      registry:
        from_secret: REGISTRY_HOST
      tags: latest
      username: 
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASSWORD
    when:
      event: push

  depl:
    image: appleboy/drone-ssh
    settings:
      host: ${SERVER_HOST}
      username: ${SERVER_USER}
      key: ${SERVER_KEY}
      port: 22
      command_timeout: 2m
      script:
        - ${SERVER_DEPLOY_CMD}
    when:
      event: push

