pipeline:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Containerfile
      platforms: linux/amd64
      repo: docker-registry4.napuu.xyz/tgvideobot2
      registry:
        from_secret: registry-host
      tags: latest
      username: 
        from_secret: registry-user
      password:
        from_secret: registry-password
    when:
      event: push

  depl:
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: server-host
      username:
        from_secret: server-user
      key:
        from_secret: server-key
      port: 22
      command_timeout: 2m
      script:
        - /usr/local/bin/kubectl rollout restart deployment tgvideobot2
    when:
      event: push

