pipeline:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Containerfile
      platforms: linux/amd64
      repo: registry-internal.default.svc.cluster.local/testings3
      registry:
        from_secret: registry-host
      tags: latest
      username: 
        from_secret: registry-user
      password:
        from_secret: registry-password
    when:
      event: push

