pipeline:
  build:
    image: plugins/docker
    pull: never
    settings:
      repo: docker-registry2.napuu.xyz/bottitesti
      tags: latest
      secret: id=mysecret,src=secret-file
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
