branches: main

pipeline:
  publish:
    image: plugins/docker
    settings:
      dockerfile: Containerfile
      repo: docker-registryr.napuu.xyz/testings3
      tags: latest
      username: 
        from_secret: registry-user
      password:
        from_secret: registry-password
    when:
      event: push
