branches: main

pipeline:

  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Containerfile
      platforms: linux/amd64
      repo: container-registry.default.svc.cluster.local:5000/testings3
      tags: latest
      username: 
        from_secret: registry-user
      password:
        from_secret: registry-password
    when:
      event: push
