kind: pipeline
name: default

steps:
- name: build dummy docker file and publish
  image: plugins/docker
  pull: never
  settings:
    repo: docker-registry2.napuu.xyz/testings2
    tags: latest
    username:
      from_secret: registry-user
    password:
      from_secret: registry-password
