version: "3.2"
services:
  message-queue:
    image: rabbitmq:3
  ingester:
    build:
      context: .
    depends_on:
      - message-queue
    volumes:
      - $PWD/config.edn:/app/config.edn
    command: java -jar out.jar ingester
  handler:
    build:
      context: .
    depends_on:
      - message-queue
    volumes:
      - $PWD/config.edn:/app/config.edn
    command: java -jar out.jar handler