name: Container Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # sunday 04:05
    - cron:  '5 4 * * 0'



jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Container image
      run: podman build . --file Containerfile --tag tgbot1:latest

    - name: Push To Registry
      uses: redhat-actions/push-to-registry@v2.5.1
      with:
        image: tgbot1
        tags: latest
        registry: ${{ secrets.REGISTRY_HOSTNAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
